---
- hosts: all
  tasks: 
    - name: install modules
      command: echo "npm install mysql2 disyUI socket.io"
      register: register
      state: present

    - name: enviroment node
      command: echo "npm install"
      register: register
      state: present

    - name: enviroment frontend
      command: echo "npm --prefix ./gpart install ./gpart npm --global"
      register: register
      state: present

    - name: create DB
      command: echo "node ./database/1_createDatabase/createDatabase.js"
      register: register
      state: present
      
    - name: create Table
      command: echo "node ./database/1_createDatabase/createTable.js"
      register: register
      state: present